// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnBCf1TKycbg0FFWPhNwkvVGv1Iy2hNP4',
    appId: '1:37314274951:web:cb4a22dd009bbb6c98fa22',
    messagingSenderId: '37314274951',
    projectId: 'pizza-shop-83cb3',
    authDomain: 'pizza-shop-83cb3.firebaseapp.com',
    storageBucket: 'pizza-shop-83cb3.firebasestorage.app',
    measurementId: 'G-RE6NCYCR31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTrmAUJH9U4OrUYAk9vkdCJk1m7tpXfI',
    appId: '1:37314274951:android:2623168dc03368fb98fa22',
    messagingSenderId: '37314274951',
    projectId: 'pizza-shop-83cb3',
    storageBucket: 'pizza-shop-83cb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0zmrcU1SqUZ5CHZgTYLlJOSh4deI23c',
    appId: '1:37314274951:ios:c153eb35b1972a2b98fa22',
    messagingSenderId: '37314274951',
    projectId: 'pizza-shop-83cb3',
    storageBucket: 'pizza-shop-83cb3.firebasestorage.app',
    iosBundleId: 'com.shafaatullah.pizzashop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU0zmrcU1SqUZ5CHZgTYLlJOSh4deI23c',
    appId: '1:37314274951:ios:c153eb35b1972a2b98fa22',
    messagingSenderId: '37314274951',
    projectId: 'pizza-shop-83cb3',
    storageBucket: 'pizza-shop-83cb3.firebasestorage.app',
    iosBundleId: 'com.shafaatullah.pizzashop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnBCf1TKycbg0FFWPhNwkvVGv1Iy2hNP4',
    appId: '1:37314274951:web:59df766bb69abfbf98fa22',
    messagingSenderId: '37314274951',
    projectId: 'pizza-shop-83cb3',
    authDomain: 'pizza-shop-83cb3.firebaseapp.com',
    storageBucket: 'pizza-shop-83cb3.firebasestorage.app',
    measurementId: 'G-DMTT7756J0',
  );
}
